name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        arr:
          - arr 1
          - arr 2
          - arr 3

    steps:
      - name: Run a one-line script
        run: echo Running for ${{matrix.arr}}
