name: reusable-workflow
on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: false

jobs:
  set-strategy:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo $(fromJSON({[\"3.1-sdk\",\"5.0-sdk\",\"6.0-sdk\"]}))

  build:
    runs-on: ubuntu-latest
    needs: [ set-strategy ]

    strategy:
      matrix:
        tags: ${{fromJSON(needs.set-strategy.outputs.matrix)}}

    steps:
      - name: dispatch tags array
        id: dispatch-tags-array
        if: "${{ inputs.tags != ''}}"
        run: |
          echo strategy round ${{matrix.tags}}
