name: reusable-workflow-json-file
on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: false

jobs:
  set-strategy:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with: 
          path: './'
      - id: set-matrix
        run: |
          echo Setting matrix output from file
          JSON=$(cat ${{inputs.tags}})
          echo "::set-output name=matrix::${JSON//'%'/'%25'}"

  build:
    runs-on: ubuntu-latest
    needs: [ set-strategy ]

    strategy:
      matrix:
        tags: ${{fromJSON(needs.set-strategy.outputs.matrix)}}

    steps:
      - name: dispatch tags array
        id: dispatch-tags-array
        # if: "${{ inputs.tags != ''}}"
        run: |
          echo strategy round ${{matrix.tags}}
  
  condition-job-true:
    runs-on: ubuntu-latest
    if: "${{ inputs.tags != ''}}"

    steps:
      - name: log if true
        id: log
        run: |
          echo inputs.tags are set

  condition-job-false:
    runs-on: ubuntu-latest
    if: "${{ inputs.tags == ''}}"

    steps:
      - name: log if false
        id: log
        run: |
          echo inputs.tags are set
  
  condition-step:
    runs-on: ubuntu-latest
    steps:
      - if: "${{ inputs.tags != ''}}"
        run: echo 'This will run only if the inputs.tags is set'
      - if: "${{ inputs.tags == ''}}"
        run: echo 'This will run only if the inputs.tags is empty'