name: reusable-workflow-json-file
on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: false

jobs:
  set-strategy:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with: 
          path: './'
      - id: set-matrix
        run: |
          echo Setting matrix output from file
          JSON=$(cat ${{inputs.tags}})
          echo "::set-output name=matrix::${JSON//'%'/'%25'}"

  build:
    runs-on: ubuntu-latest
    needs: [ set-strategy ]

    strategy:
      matrix:
        tags: ${{fromJSON(needs.set-strategy.outputs.matrix)}}

    steps:
      - name: dispatch tags array
        id: dispatch-tags-array
        # if: "${{ inputs.tags != ''}}"
        run: |
          echo strategy round ${{matrix.tags}}
