name: reusable-workflow
on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: false

jobs:
  set-strategy:
    runs-on: ubuntu-latest
    outputs:
      matrix1: ${{ steps.set-matrix.outputs.matrix1 }}
      matrix2: ${{ steps.set-matrix.outputs.matrix2 }}
    steps:
      - uses: actions/checkout@v2
        with: 
          path: './'    
      - id: set-matrix
        run: |
          echo Setting matrix output from parent workflow
          echo "Input tags ${{ inputs.tags }}"
          echo "Input tags fromJSON ${{ fromJSON(inputs.tags) }}"
          echo "::set-output name=matrix1::${{inputs.tags}}"
          echo
          echo Setting matrix output from file
          JSON=$(cat ./settings.json)
          echo "file content ${JSON}"
          echo "JSON content ${JSON//'%'/'%25'}"
          echo "::set-output name=matrix2::${JSON//'%'/'%25'}"

  build:
    runs-on: ubuntu-latest
    needs: [ set-strategy ]

    strategy:
      matrix:
        tags: ${{fromJSON(needs.set-strategy.outputs.matrix2)}}
        # tags: ${{ fromJSON([1,2,3])}}

    steps:
      - name: dispatch tags array
        id: dispatch-tags-array
        # if: "${{ inputs.tags != ''}}"
        run: |
          echo strategy round ${{matrix.tags}}
