name: reusable-workflow
on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tags: ["test 1", "test 2", "test 3"]

    steps:
      - name: dispatch tags array
        id: dispatch-tags-array
        if: "${{ inputs.tags != ''}}"
        run: |
          echo Input ${{inputs.tags}}
          echo strategy round ${{matrix.tags}}
