name: reusable-workflow
on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: false

jobs:
  job-one:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tags: ${{ inputs.tags | jq }}

    steps:
      - name: dispatch tags array
        id: dispatch-tags-array
        if: "${{ inputs.tags != ''}}"
        run: |
          echo Running tag ${{inputs.tags}}
