name: simple-workflow

on:
  workflow_dispatch:

jobs:
  run-builds:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arr:
          - 3.1-sdk
          - 5.0-sdk
          - 6.0-sdk

    steps:
      - run: echo strategy round ${{matrix.arr}}